try to fetch labels properly

diff --git a/.github/workflows/changelog.yml b/.github/workflows/changelog.yml
--- a/.github/workflows/changelog.yml
+++ b/.github/workflows/changelog.yml
@@ -17,18 +17,18 @@ jobs:
           set -euo pipefail
 
           # Obtain all labels set to the PR
-          labels='${{ toJson(github.event.pull_request.labels.*.name) }}'
+          labels="${{ join(github.event.pull_request.labels.*.name, '\n') }}"
 
           # If the labels contains feature, bug or api-change then automatically require the 'changelog-required' label
-          if echo "$labels" | grep -Eq '"(feature|bug|api-change)"'; then
-            if ! echo "$labels" | grep -q '"changelog-required"'; then
+          if echo "$labels" | grep -Eq '^(feature|bug|api-change)$'; then
+            if ! echo "$labels" | grep -q '^changelog-required$'; then
               echo "PR has 'feature', 'bug', or 'api-change' label but is missing 'changelog-required'."
               exit 1
             fi
           fi
 
           # Now we look for 'changelog-required' label
-          if echo "$labels" | grep -q "changelog-required"; then
+          if echo "$labels" | grep -q "^changelog-required$"; then
             echo "Label 'changelog-required' is set. Checking for fragments in docs/release-notes/*.rst..."
 
             if ! git diff --name-only origin/${{ github.base_ref }}... | grep -q '^docs/release-notes/.*\.rst$'; then
